name: Rebase Alpha and Beta on Main Merge

on:
  push:
    branches:
      - main

jobs:
  rebase-on-main-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup git
      run: |
          git config --global user.email "pinedavictor095@gmail.com"
          git config --global user.name "PinedaVictor"

    - name: Rebase Alpha Branch
      run: |
        git fetch origin alpha
        git checkout alpha
        git pull --rebase --force origin main
        # Handle merge conflicts
        git diff --name-only --diff-filter=U | xargs -I {} git checkout --theirs -- '{}'
        git add .
        git rebase --continue
        git push origin alpha

    - name: Rebase Beta Branch
      run: |
        git fetch origin beta
        git checkout beta
        git pull --rebase --force origin main
        # Handle merge conflicts
        git diff --name-only --diff-filter=U | xargs -I {} git checkout --theirs -- '{}'
        git add .
        git rebase --continue
        git push origin beta
