name: Rebase Alpha and Beta on Main Merge

on:
  push:
    branches:
      - main

jobs:
  rebase-on-main-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup git
      run: |
          git config --global user.email "pinedavictor095@gmail.com"
          git config --global user.name "PinedaVictor"

    - name: Rebase Alpha Branch
      run: |
        git fetch origin alpha
        git checkout alpha
        git rebase origin/main || true  # Continue even if conflicts occur

        # Handle merge conflicts (you may need to update this based on your needs)
        git diff --name-only --diff-filter=U | xargs git checkout --ours --
        git add .
        git rebase --continue

        git push origin alpha

    - name: Rebase Beta Branch
      run: |
        git fetch origin beta
        git checkout beta
        git rebase origin/main || true  # Continue even if conflicts occur
        git diff --name-only --diff-filter=U | xargs git checkout --ours --
        git add .
        git rebase --continue
        git push origin beta
